<?php
//000000000600a:5:{i:0;a:14:{s:2:"id";i:52;s:7:"content";s:281:"我发表了一个新的帖子【发表的新帖字】：<a class="label label-badge" href="http://localhost/dev/opensns/index.php?s=/forum/index/detail/id/33" target="_blank"><i class="icon-link" title="http://localhost/dev/opensns/index.php?s=/forum/index/detail/id/33"></i></a> ";s:11:"create_time";i:1443146217;s:4:"type";s:4:"feed";s:4:"data";a:0:{}s:10:"weibo_data";a:0:{}s:13:"comment_count";i:0;s:12:"repost_count";i:0;s:10:"can_delete";b:0;s:6:"is_top";s:1:"0";s:3:"uid";s:1:"1";s:12:"fetchContent";s:306:"<p class='word-wrap'>我发表了一个新的帖子【发表的新帖字】：<a class="label label-badge" href="http://localhost/dev/opensns/index.php?s=/forum/index/detail/id/33" target="_blank"><i class="icon-link" title="http://localhost/dev/opensns/index.php?s=/forum/index/detail/id/33"></i></a> </p>";s:4:"from";s:0:"";s:4:"user";a:6:{s:3:"uid";s:1:"1";s:8:"nickname";s:6:"测试";s:8:"avatar64";s:53:"/dev/opensns/Uploads/Avatar/1/56039892b7f43_64_64.jpg";s:9:"space_url";s:56:"/dev/opensns/index.php?s=/ucenter/index/index/uid/1.html";s:9:"rank_link";a:0:{}s:5:"title";s:10:"Lv2 试用";}}i:1;a:14:{s:2:"id";i:51;s:7:"content";s:265:"我发表了一个新的帖子【af】：<a class="label label-badge" href="http://localhost/dev/opensns/index.php?s=/forum/index/detail/id/32" target="_blank"><i class="icon-link" title="http://localhost/dev/opensns/index.php?s=/forum/index/detail/id/32"></i></a> ";s:11:"create_time";i:1443144045;s:4:"type";s:4:"feed";s:4:"data";a:0:{}s:10:"weibo_data";a:0:{}s:13:"comment_count";i:0;s:12:"repost_count";i:0;s:10:"can_delete";b:0;s:6:"is_top";s:1:"0";s:3:"uid";s:1:"1";s:12:"fetchContent";s:290:"<p class='word-wrap'>我发表了一个新的帖子【af】：<a class="label label-badge" href="http://localhost/dev/opensns/index.php?s=/forum/index/detail/id/32" target="_blank"><i class="icon-link" title="http://localhost/dev/opensns/index.php?s=/forum/index/detail/id/32"></i></a> </p>";s:4:"from";s:0:"";s:4:"user";a:6:{s:3:"uid";s:1:"1";s:8:"nickname";s:6:"测试";s:8:"avatar64";s:53:"/dev/opensns/Uploads/Avatar/1/56039892b7f43_64_64.jpg";s:9:"space_url";s:56:"/dev/opensns/index.php?s=/ucenter/index/index/uid/1.html";s:9:"rank_link";a:0:{}s:5:"title";s:10:"Lv2 试用";}}i:2;a:14:{s:2:"id";i:50;s:7:"content";s:11:"3123123213 ";s:11:"create_time";i:1442991151;s:4:"type";s:6:"repost";s:4:"data";a:2:{s:6:"source";N;s:8:"sourceId";i:49;}s:10:"weibo_data";a:2:{s:6:"source";N;s:8:"sourceId";i:49;}s:13:"comment_count";i:0;s:12:"repost_count";i:0;s:10:"can_delete";b:0;s:6:"is_top";s:1:"0";s:3:"uid";s:3:"100";s:12:"fetchContent";s:1535:"    <p class="word-wrap">3123123213 </p>

    <div class="triangle sanjiao" style="margin-left: 20px;border-bottom: 10px solid #e8e8e8;"></div>
    <div class="triangle_up sanjiao" style="margin-left: 20px;border-bottom: 10px solid #f1f1f1;"></div>
    <div  style="border: 1px solid #e8e8e8;padding: 10px;margin-bottom: 20px; background: #f1f1f1">
            <div>  <a ucard="100"     href="/dev/opensns/index.php?s=/ucenter/index/index/uid/100.html">@richard</a></div>
        <p class='word-wrap'>23213<img src='/dev/opensns/Application/Core/Static/images/expression/miniblog/fan.gif' /><img src='/dev/opensns/Application/Core/Static/images/expression/miniblog/keai.gif' /><img src='/dev/opensns/Application/Core/Static/images/expression/miniblog/kuaikule.gif' /> </p>        <span class="text-primary pull-left" style="font-size: 12px;"><a href="/dev/opensns/index.php?s=/weibo/index/weibodetail/id/49.html">09月23日 14:50</a>   </span>
        <span class="text-primary pull-right" style="font-size: 12px;"><a href="/dev/opensns/index.php?s=/weibo/index/weibodetail/id/49.html"> 原微博转发（1）</a>  </span>
        &nbsp;    </div>
    <script>
            var html='<a href="/dev/opensns/index.php?s=/ucenter/index/index/uid/100.html" ucard="100" style="position: absolute;margin-top: 32px;margin-left: -32px;"><img src="/dev/opensns/Uploads/Avatar/100/55e556bea67d7_32_32.jpg"   class="avatar-img"   style="width: 32px;"/> </a>';
            $('#weibo_50').find('.s_avatar').after(html);
        </script>";s:4:"from";s:0:"";s:4:"user";a:6:{s:3:"uid";s:3:"100";s:8:"nickname";s:7:"richard";s:8:"avatar64";s:55:"/dev/opensns/Uploads/Avatar/100/55e556bea67d7_64_64.jpg";s:9:"space_url";s:58:"/dev/opensns/index.php?s=/ucenter/index/index/uid/100.html";s:9:"rank_link";a:0:{}s:5:"title";s:10:"Lv2 试用";}}i:3;a:14:{s:2:"id";i:49;s:7:"content";s:267:"23213<img src='/dev/opensns/Application/Core/Static/images/expression/miniblog/fan.gif' /><img src='/dev/opensns/Application/Core/Static/images/expression/miniblog/keai.gif' /><img src='/dev/opensns/Application/Core/Static/images/expression/miniblog/kuaikule.gif' /> ";s:11:"create_time";i:1442991055;s:4:"type";s:4:"feed";s:4:"data";a:0:{}s:10:"weibo_data";a:0:{}s:13:"comment_count";i:0;s:12:"repost_count";i:1;s:10:"can_delete";b:0;s:6:"is_top";s:1:"0";s:3:"uid";s:3:"100";s:12:"fetchContent";s:292:"<p class='word-wrap'>23213<img src='/dev/opensns/Application/Core/Static/images/expression/miniblog/fan.gif' /><img src='/dev/opensns/Application/Core/Static/images/expression/miniblog/keai.gif' /><img src='/dev/opensns/Application/Core/Static/images/expression/miniblog/kuaikule.gif' /> </p>";s:4:"from";s:0:"";s:4:"user";a:6:{s:3:"uid";s:3:"100";s:8:"nickname";s:7:"richard";s:8:"avatar64";s:55:"/dev/opensns/Uploads/Avatar/100/55e556bea67d7_64_64.jpg";s:9:"space_url";s:58:"/dev/opensns/index.php?s=/ucenter/index/index/uid/100.html";s:9:"rank_link";a:0:{}s:5:"title";s:10:"Lv2 试用";}}i:4;a:14:{s:2:"id";i:48;s:7:"content";s:141:"123213 <a class='label label-badge label-info'  href="/dev/opensns/index.php?s=/weibo/topic/index/topk/213.html" target="_blank">#213# </a>  ";s:11:"create_time";i:1442991040;s:4:"type";s:4:"feed";s:4:"data";a:0:{}s:10:"weibo_data";a:0:{}s:13:"comment_count";i:0;s:12:"repost_count";i:0;s:10:"can_delete";b:0;s:6:"is_top";s:1:"0";s:3:"uid";s:3:"100";s:12:"fetchContent";s:166:"<p class='word-wrap'>123213 <a class='label label-badge label-info'  href="/dev/opensns/index.php?s=/weibo/topic/index/topk/213.html" target="_blank">#213# </a>  </p>";s:4:"from";s:0:"";s:4:"user";a:6:{s:3:"uid";s:3:"100";s:8:"nickname";s:7:"richard";s:8:"avatar64";s:55:"/dev/opensns/Uploads/Avatar/100/55e556bea67d7_64_64.jpg";s:9:"space_url";s:58:"/dev/opensns/index.php?s=/ucenter/index/index/uid/100.html";s:9:"rank_link";a:0:{}s:5:"title";s:10:"Lv2 试用";}}}
?>